server:
  port: 8082

spring:
  application:
    name: db-service
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    properties:
      max:
        metadata:
          cache:
            entries: 256
      metadata:
        max:
          age:
            ms: 100000

    consumer:
      topic1: userProfile
      topic2: userProfileVisitTopic
      topic3: userProfileListTopic
      topicRes: response_notification
      topic4: profileVisitsList
      bootstrap-servers: localhost:9092
      group-id: userProfile
      auto-offset-reset: latest
      value-serializer: org.apache.kafka.common.support.serializer.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-commit-interval: 2000
